# In _config.yml

title: "Cheick Camara"
email: "cheick.camara@exemple.com"
description: "Ph.D. Candidate in Economics – CERDI / UCA / CNRS / IRD"
url: "https://chcamara1.github.io"
baseurl: ""  # do not change

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation links
header_pages:
  - index.md
  - about.md
  - cv.md
  - publications.md
